package com.today36524.schoolsoa

        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.dapeng.remoting.BaseCommonServiceClient
        import com.today36524.schoolsoa.LessonServiceCodec._
        import scala.concurrent.{Future, Promise}
        import java.util.function.BiConsumer

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        **/
        object LessonServiceAsyncClient extends BaseCommonServiceClient("com.today36524.schoolsoa.service.LessonService", "1.0.0"){

        override def isSoaTransactionalProcess: Boolean = {

          var isSoaTransactionalProcess = false
          
          isSoaTransactionalProcess
        }

        
            /**
            * 

    query lesson

            **/
            def findLessonByName(name:String , timeout: Long) : scala.concurrent.Future[com.today36524.schoolsoa.bean.Lesson] = {

            initContext("findLessonByName");

            try {
              val _responseFuture = sendBaseAsync(findLessonByName_args(name), new FindLessonByName_argsSerializer(), new FindLessonByName_resultSerializer(), timeout).asInstanceOf[java.util.concurrent.CompletableFuture[findLessonByName_result]]

              val promise = Promise[com.today36524.schoolsoa.bean.Lesson]()

              _responseFuture.whenComplete(new BiConsumer[findLessonByName_result, Throwable]{

              override def accept(r: findLessonByName_result, e: Throwable): Unit = {
                if(e != null)
                  promise.failure(e)
                else
                  promise.success(r.success)
                }
              })
              promise.future
            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }finally {
              destoryContext()
            }
          }
          
            /**
            * 
            **/
            def findAllLessons( timeout: Long) : scala.concurrent.Future[List[com.today36524.schoolsoa.bean.Lesson]] = {

            initContext("findAllLessons");

            try {
              val _responseFuture = sendBaseAsync(findAllLessons_args(), new FindAllLessons_argsSerializer(), new FindAllLessons_resultSerializer(), timeout).asInstanceOf[java.util.concurrent.CompletableFuture[findAllLessons_result]]

              val promise = Promise[List[com.today36524.schoolsoa.bean.Lesson]]()

              _responseFuture.whenComplete(new BiConsumer[findAllLessons_result, Throwable]{

              override def accept(r: findAllLessons_result, e: Throwable): Unit = {
                if(e != null)
                  promise.failure(e)
                else
                  promise.success(r.success)
                }
              })
              promise.future
            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }finally {
              destoryContext()
            }
          }
          

      }
      