package com.today36524.schoolsoa

        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.dapeng.remoting.BaseCommonServiceClient
        import com.today36524.schoolsoa.ScoreServiceCodec._

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        **/
        object ScoreServiceClient extends BaseCommonServiceClient("com.today36524.schoolsoa.service.ScoreService", "1.0.0"){

        override def isSoaTransactionalProcess: Boolean = {

          var isSoaTransactionalProcess = false
          
          isSoaTransactionalProcess
        }

        
         /**
         * 

    query student

         **/

            def findScoreByStudentIdAndLessonName(id:String ) : com.today36524.schoolsoa.bean.Score = {

            initContext("findScoreByStudentIdAndLessonName");

            try {
              val response = sendBase(findScoreByStudentIdAndLessonName_args(id), new FindScoreByStudentIdAndLessonName_argsSerializer(), new FindScoreByStudentIdAndLessonName_resultSerializer())

              response.success

            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }
            finally {
              destoryContext();
            }
            }
          
         /**
         * 
         **/

            def findScoresByStudentId(studentId:String ) : List[com.today36524.schoolsoa.bean.Score] = {

            initContext("findScoresByStudentId");

            try {
              val response = sendBase(findScoresByStudentId_args(studentId), new FindScoresByStudentId_argsSerializer(), new FindScoresByStudentId_resultSerializer())

              response.success

            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }
            finally {
              destoryContext();
            }
            }
          
         /**
         * 
         **/

            def findAllScores() : List[com.today36524.schoolsoa.bean.Score] = {

            initContext("findAllScores");

            try {
              val response = sendBase(findAllScores_args(), new FindAllScores_argsSerializer(), new FindAllScores_resultSerializer())

              response.success

            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }
            finally {
              destoryContext();
            }
            }
          

        /**
        * getServiceMetadata
        **/
        @throws[SoaException]
        def getServiceMetadata: String = {
          initContext("getServiceMetadata")
          try {
            val _request = new getServiceMetadata_args()
            val _response = sendBase(_request, new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer())
            _response.success
          }catch{
            case e: SoaException => throw e
            case e: TException => throw new SoaException(e)
          }
          finally {
            destoryContext()
          }
        }

        }
      