package com.today36524.schoolsoa
        import com.today36524.schoolsoa.bean.serializer._;

        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.org.apache.thrift.protocol._

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/
        object ScoreServiceCodec {

        
            case class findScoreByStudentIdAndLessonName_args(id:String)

            case class findScoreByStudentIdAndLessonName_result(success:com.today36524.schoolsoa.bean.Score)

            class FindScoreByStudentIdAndLessonName_argsSerializer extends TCommonBeanSerializer[findScoreByStudentIdAndLessonName_args]{
            
      @throws[TException]
      override def read(iprot: TProtocol): findScoreByStudentIdAndLessonName_args = {

        var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
        iprot.readStructBegin()

      var id: String = null
        

      while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

        schemeField = iprot.readFieldBegin

        schemeField.id match {
          
              case 1 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => id = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
        }
      }

      iprot.readFieldEnd
      iprot.readStructEnd

      val bean = findScoreByStudentIdAndLessonName_args(id = id)
      validate(bean)

      bean
      }
    
      @throws[TException]
      override def write(bean: findScoreByStudentIdAndLessonName_args, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("findScoreByStudentIdAndLessonName_args"))

      
            {
            val elem0 = bean.id 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("id", com.isuwang.org.apache.thrift.protocol.TType.STRING, 1.asInstanceOf[Short]))
            oprot.writeString(elem0)
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
      @throws[TException]
      override def validate(bean: findScoreByStudentIdAndLessonName_args): Unit = {
      
              if(bean.id == null)
              throw new SoaException(SoaBaseCode.NotNull, "id字段不允许为空")
            
    }
    

            override def toString(bean: findScoreByStudentIdAndLessonName_args): String = if(bean == null)  "null" else bean.toString
            }

            class FindScoreByStudentIdAndLessonName_resultSerializer extends TCommonBeanSerializer[findScoreByStudentIdAndLessonName_result]{

            @throws[TException]
            override def read(iprot: TProtocol): findScoreByStudentIdAndLessonName_result = {

              var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
              iprot.readStructBegin

              var success : com.today36524.schoolsoa.bean.Score = null

              while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

                schemeField = iprot.readFieldBegin

                schemeField.id match {
                    case 0 =>
                       schemeField.`type` match {
                          case com.isuwang.org.apache.thrift.protocol.TType.STRUCT =>  success = new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().read(iprot)
                          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                  }
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                }

                iprot.readFieldEnd
              }

              iprot.readStructEnd
              val bean = findScoreByStudentIdAndLessonName_result(success)
              validate(bean)

              bean
            }

            
      @throws[TException]
      override def write(bean: findScoreByStudentIdAndLessonName_result, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("findScoreByStudentIdAndLessonName_result"))

      
            {
            val elem0 = bean.success 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("success", com.isuwang.org.apache.thrift.protocol.TType.STRUCT, 0.asInstanceOf[Short]))
             new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().write(elem0, oprot)
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
            
      @throws[TException]
      override def validate(bean: findScoreByStudentIdAndLessonName_result): Unit = {
      
              if(bean.success == null)
              throw new SoaException(SoaBaseCode.NotNull, "success字段不允许为空")
            
                if(bean.success != null)
                new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().validate(bean.success)
              
    }
    

            override def toString(bean: findScoreByStudentIdAndLessonName_result): String = if(bean == null)  "null" else bean.toString
          }

            class findScoreByStudentIdAndLessonName extends SoaProcessFunction[com.today36524.schoolsoa.service.ScoreService, findScoreByStudentIdAndLessonName_args, findScoreByStudentIdAndLessonName_result, FindScoreByStudentIdAndLessonName_argsSerializer,  FindScoreByStudentIdAndLessonName_resultSerializer]("findScoreByStudentIdAndLessonName", new FindScoreByStudentIdAndLessonName_argsSerializer(), new FindScoreByStudentIdAndLessonName_resultSerializer()){

            override def isOneway: Boolean = false

            override def getEmptyArgsInstance: findScoreByStudentIdAndLessonName_args = null


            @throws[TException]
            def getResult(iface: com.today36524.schoolsoa.service.ScoreService, args: findScoreByStudentIdAndLessonName_args):findScoreByStudentIdAndLessonName_result = {

              val _result = iface.findScoreByStudentIdAndLessonName(args.id)
              findScoreByStudentIdAndLessonName_result(_result )
            }
          }
          
            case class findScoresByStudentId_args(studentId:String)

            case class findScoresByStudentId_result(success:List[com.today36524.schoolsoa.bean.Score])

            class FindScoresByStudentId_argsSerializer extends TCommonBeanSerializer[findScoresByStudentId_args]{
            
      @throws[TException]
      override def read(iprot: TProtocol): findScoresByStudentId_args = {

        var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
        iprot.readStructBegin()

      var studentId: String = null
        

      while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

        schemeField = iprot.readFieldBegin

        schemeField.id match {
          
              case 1 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRING => studentId = iprot.readString
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
        }
      }

      iprot.readFieldEnd
      iprot.readStructEnd

      val bean = findScoresByStudentId_args(studentId = studentId)
      validate(bean)

      bean
      }
    
      @throws[TException]
      override def write(bean: findScoresByStudentId_args, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("findScoresByStudentId_args"))

      
            {
            val elem0 = bean.studentId 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("studentId", com.isuwang.org.apache.thrift.protocol.TType.STRING, 1.asInstanceOf[Short]))
            oprot.writeString(elem0)
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
      @throws[TException]
      override def validate(bean: findScoresByStudentId_args): Unit = {
      
              if(bean.studentId == null)
              throw new SoaException(SoaBaseCode.NotNull, "studentId字段不允许为空")
            
    }
    

            override def toString(bean: findScoresByStudentId_args): String = if(bean == null)  "null" else bean.toString
            }

            class FindScoresByStudentId_resultSerializer extends TCommonBeanSerializer[findScoresByStudentId_result]{

            @throws[TException]
            override def read(iprot: TProtocol): findScoresByStudentId_result = {

              var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
              iprot.readStructBegin

              var success : List[com.today36524.schoolsoa.bean.Score] = List.empty

              while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

                schemeField = iprot.readFieldBegin

                schemeField.id match {
                    case 0 =>
                       schemeField.`type` match {
                          case com.isuwang.org.apache.thrift.protocol.TType.LIST =>  success = {
        val _list0 : com.isuwang.org.apache.thrift.protocol.TList = iprot.readListBegin
        val _result0 = (0 until _list0.size).map(_ => {new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().read(iprot)}).toList
        iprot.readListEnd
        _result0
        }
                          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                  }
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                }

                iprot.readFieldEnd
              }

              iprot.readStructEnd
              val bean = findScoresByStudentId_result(success)
              validate(bean)

              bean
            }

            
      @throws[TException]
      override def write(bean: findScoresByStudentId_result, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("findScoresByStudentId_result"))

      
            {
            val elem0 = bean.success 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("success", com.isuwang.org.apache.thrift.protocol.TType.LIST, 0.asInstanceOf[Short]))
            
        oprot.writeListBegin(new com.isuwang.org.apache.thrift.protocol.TList(com.isuwang.org.apache.thrift.protocol.TType.STRUCT, elem0.size))
        elem0.foreach(elem1 => { new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().write(elem1, oprot)})
        oprot.writeListEnd
      
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
            
      @throws[TException]
      override def validate(bean: findScoresByStudentId_result): Unit = {
      
              if(bean.success == null)
              throw new SoaException(SoaBaseCode.NotNull, "success字段不允许为空")
            
    }
    

            override def toString(bean: findScoresByStudentId_result): String = if(bean == null)  "null" else bean.toString
          }

            class findScoresByStudentId extends SoaProcessFunction[com.today36524.schoolsoa.service.ScoreService, findScoresByStudentId_args, findScoresByStudentId_result, FindScoresByStudentId_argsSerializer,  FindScoresByStudentId_resultSerializer]("findScoresByStudentId", new FindScoresByStudentId_argsSerializer(), new FindScoresByStudentId_resultSerializer()){

            override def isOneway: Boolean = false

            override def getEmptyArgsInstance: findScoresByStudentId_args = null


            @throws[TException]
            def getResult(iface: com.today36524.schoolsoa.service.ScoreService, args: findScoresByStudentId_args):findScoresByStudentId_result = {

              val _result = iface.findScoresByStudentId(args.studentId)
              findScoresByStudentId_result(_result )
            }
          }
          
            case class findAllScores_args()

            case class findAllScores_result(success:List[com.today36524.schoolsoa.bean.Score])

            class FindAllScores_argsSerializer extends TCommonBeanSerializer[findAllScores_args]{
            
      @throws[TException]
      override def read(iprot: TProtocol): findAllScores_args = {

        var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
        iprot.readStructBegin()

      

      while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

        schemeField = iprot.readFieldBegin

        schemeField.id match {
          
          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
        }
      }

      iprot.readFieldEnd
      iprot.readStructEnd

      val bean = findAllScores_args()
      validate(bean)

      bean
      }
    
      @throws[TException]
      override def write(bean: findAllScores_args, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("findAllScores_args"))

      
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
      @throws[TException]
      override def validate(bean: findAllScores_args): Unit = {
      
    }
    

            override def toString(bean: findAllScores_args): String = if(bean == null)  "null" else bean.toString
            }

            class FindAllScores_resultSerializer extends TCommonBeanSerializer[findAllScores_result]{

            @throws[TException]
            override def read(iprot: TProtocol): findAllScores_result = {

              var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
              iprot.readStructBegin

              var success : List[com.today36524.schoolsoa.bean.Score] = List.empty

              while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

                schemeField = iprot.readFieldBegin

                schemeField.id match {
                    case 0 =>
                       schemeField.`type` match {
                          case com.isuwang.org.apache.thrift.protocol.TType.LIST =>  success = {
        val _list0 : com.isuwang.org.apache.thrift.protocol.TList = iprot.readListBegin
        val _result0 = (0 until _list0.size).map(_ => {new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().read(iprot)}).toList
        iprot.readListEnd
        _result0
        }
                          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                  }
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                }

                iprot.readFieldEnd
              }

              iprot.readStructEnd
              val bean = findAllScores_result(success)
              validate(bean)

              bean
            }

            
      @throws[TException]
      override def write(bean: findAllScores_result, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("findAllScores_result"))

      
            {
            val elem0 = bean.success 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("success", com.isuwang.org.apache.thrift.protocol.TType.LIST, 0.asInstanceOf[Short]))
            
        oprot.writeListBegin(new com.isuwang.org.apache.thrift.protocol.TList(com.isuwang.org.apache.thrift.protocol.TType.STRUCT, elem0.size))
        elem0.foreach(elem1 => { new com.today36524.schoolsoa.bean.serializer.ScoreSerializer().write(elem1, oprot)})
        oprot.writeListEnd
      
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
            
      @throws[TException]
      override def validate(bean: findAllScores_result): Unit = {
      
              if(bean.success == null)
              throw new SoaException(SoaBaseCode.NotNull, "success字段不允许为空")
            
    }
    

            override def toString(bean: findAllScores_result): String = if(bean == null)  "null" else bean.toString
          }

            class findAllScores extends SoaProcessFunction[com.today36524.schoolsoa.service.ScoreService, findAllScores_args, findAllScores_result, FindAllScores_argsSerializer,  FindAllScores_resultSerializer]("findAllScores", new FindAllScores_argsSerializer(), new FindAllScores_resultSerializer()){

            override def isOneway: Boolean = false

            override def getEmptyArgsInstance: findAllScores_args = null


            @throws[TException]
            def getResult(iface: com.today36524.schoolsoa.service.ScoreService, args: findAllScores_args):findAllScores_result = {

              val _result = iface.findAllScores()
              findAllScores_result(_result )
            }
          }
          

        case class getServiceMetadata_args()

        case class getServiceMetadata_result(success: String)

        class GetServiceMetadata_argsSerializer extends TCommonBeanSerializer[getServiceMetadata_args] {

          @throws[TException]
          override def read(iprot: TProtocol): getServiceMetadata_args = {

            iprot.readStructBegin

            var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null

            while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {
              schemeField = iprot.readFieldBegin
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
              iprot.readFieldEnd
            }

            iprot.readStructEnd

            val bean = getServiceMetadata_args()
            validate(bean)

            bean
          }

          @throws[TException]
          override def write(bean: getServiceMetadata_args, oproto: TProtocol): Unit = {
            validate(bean)
            oproto.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("getServiceMetadata_args"))

            oproto.writeFieldStop
            oproto.writeStructEnd
          }

          @throws[TException]
          override def validate(bean: getServiceMetadata_args): Unit = {}

          override def toString(bean: getServiceMetadata_args): String = if (bean == null) "null" else bean.toString
        }



        class GetServiceMetadata_resultSerializer extends TCommonBeanSerializer[getServiceMetadata_result] {
          @throws[TException]
          override def read(iprot: TProtocol): getServiceMetadata_result = {
            iprot.readStructBegin

            var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null

            var success: String = null

            while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {
              schemeField = iprot.readFieldBegin

              schemeField.id match {
                case 0 =>
                schemeField.`type` match {
                  case com.isuwang.org.apache.thrift.protocol.TType.STRING => success = iprot.readString
                  case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
                }
                case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
              }
              iprot.readFieldEnd
            }

            iprot.readStructEnd
            val bean = getServiceMetadata_result(success)
            validate(bean)

            bean
          }

          @throws[TException]
          override def write(bean: getServiceMetadata_result, oproto: TProtocol): Unit = {
            validate(bean)
            oproto.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("getServiceMetadata_result"))

            oproto.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("success", com.isuwang.org.apache.thrift.protocol.TType.STRING, 0.asInstanceOf[Short]))
            oproto.writeString(bean.success)
            oproto.writeFieldEnd

            oproto.writeFieldStop
            oproto.writeStructEnd
          }

          @throws[TException]
          override def validate(bean: getServiceMetadata_result): Unit = {
            if (bean.success == null)
            throw new SoaException(SoaBaseCode.NotNull, "success字段不允许为空")
          }

          override def toString(bean: getServiceMetadata_result): String = if (bean == null) "null" else bean.toString

        }



  class getServiceMetadata extends SoaProcessFunction[com.today36524.schoolsoa.service.ScoreService, getServiceMetadata_args, getServiceMetadata_result, GetServiceMetadata_argsSerializer, GetServiceMetadata_resultSerializer](
  "getServiceMetadata", new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer()) {

      override def isOneway: Boolean = false

      override def getEmptyArgsInstance: getServiceMetadata_args = getServiceMetadata_args()

      @throws[TException]
      override def getResult(iface: com.today36524.schoolsoa.service.ScoreService, args: getServiceMetadata_args): getServiceMetadata_result = {

        val source = scala.io.Source.fromInputStream(ScoreServiceCodec.getClass.getClassLoader.getResourceAsStream("com.today36524.schoolsoa.service.ScoreService.xml"))
        val success = source.mkString
        source.close
        getServiceMetadata_result(success)
      }
      }

      class Processor(iface: com.today36524.schoolsoa.service.ScoreService) extends SoaCommonBaseProcessor(iface, Processor.getProcessMap)

        object Processor{

          type PF = SoaProcessFunction[com.today36524.schoolsoa.service.ScoreService, _, _, _ <: TCommonBeanSerializer[_], _ <: TCommonBeanSerializer[_]]

          def getProcessMap(): java.util.Map[String, PF] = {
             val map = new java.util.HashMap[String, PF]()
            map.put("findScoreByStudentIdAndLessonName", new findScoreByStudentIdAndLessonName)
              map.put("findScoresByStudentId", new findScoresByStudentId)
              map.put("findAllScores", new findAllScores)
              
            map.put("getServiceMetadata", new getServiceMetadata)
            map
          }

        }
        }
      