package com.today36524.schoolsoa

        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.dapeng.remoting.BaseCommonServiceClient
        import com.today36524.schoolsoa.StudentServiceCodec._

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        **/
        object StudentServiceClient extends BaseCommonServiceClient("com.today36524.schoolsoa.service.StudentService", "1.0.0"){

        override def isSoaTransactionalProcess: Boolean = {

          var isSoaTransactionalProcess = false
          
          isSoaTransactionalProcess
        }

        
         /**
         * 

    query student

         **/

            def findStudentById(id:String ) : com.today36524.schoolsoa.bean.Student = {

            initContext("findStudentById");

            try {
              val response = sendBase(findStudentById_args(id), new FindStudentById_argsSerializer(), new FindStudentById_resultSerializer())

              response.success

            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }
            finally {
              destoryContext();
            }
            }
          
         /**
         * 
         **/

            def findStudentsByClass(classId:String ) : List[com.today36524.schoolsoa.bean.Student] = {

            initContext("findStudentsByClass");

            try {
              val response = sendBase(findStudentsByClass_args(classId), new FindStudentsByClass_argsSerializer(), new FindStudentsByClass_resultSerializer())

              response.success

            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }
            finally {
              destoryContext();
            }
            }
          
         /**
         * 
         **/

            def findStudentRowsByClass(classId:String ) : List[com.today36524.schoolsoa.bean.StudentInfo] = {

            initContext("findStudentRowsByClass");

            try {
              val response = sendBase(findStudentRowsByClass_args(classId), new FindStudentRowsByClass_argsSerializer(), new FindStudentRowsByClass_resultSerializer())

              response.success

            }catch{
              case e: SoaException => throw e
              case e: TException => throw new SoaException(e)
            }
            finally {
              destoryContext();
            }
            }
          

        /**
        * getServiceMetadata
        **/
        @throws[SoaException]
        def getServiceMetadata: String = {
          initContext("getServiceMetadata")
          try {
            val _request = new getServiceMetadata_args()
            val _response = sendBase(_request, new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer())
            _response.success
          }catch{
            case e: SoaException => throw e
            case e: TException => throw new SoaException(e)
          }
          finally {
            destoryContext()
          }
        }

        }
      