
        package com.today36524.schoolsoa.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.today36524.schoolsoa.service.ClassService" , version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.ClassServiceCodec$Processor")
        trait ClassService {
        
            /**
            * 

    query class

            **/
            
            def findClassById(
            id: String ): com.today36524.schoolsoa.bean.Clazz

          
            /**
            * 
            **/
            
            def findClassesByGrade(
            gradeId: String ): List[com.today36524.schoolsoa.bean.Clazz]

          
        }
        