
        package com.today36524.schoolsoa.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

  Grade service,to query information of grades

        **/
        @Service(name ="com.today36524.schoolsoa.service.GradeService" , version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.GradeServiceCodec$Processor")
        trait GradeService {
        
            /**
            * 

    query grade

            **/
            
            def findGradeById(
            id: String ): com.today36524.schoolsoa.bean.Grade

          
            /**
            * 
            **/
            
            def findGradesBySchool(
            schoolId: String ): List[com.today36524.schoolsoa.bean.Grade]

          
        }
        