
        package com.today36524.schoolsoa.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.today36524.schoolsoa.service.LessonService" , version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.LessonServiceCodec$Processor")
        trait LessonService {
        
            /**
            * 

    query lesson

            **/
            
            def findLessonByName(
            name: String ): com.today36524.schoolsoa.bean.Lesson

          
            /**
            * 
            **/
            
            def findAllLessons(
            ): List[com.today36524.schoolsoa.bean.Lesson]

          
        }
        