
        package com.today36524.schoolsoa.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

  School service,to query information of schools

        **/
        @Service(name ="com.today36524.schoolsoa.service.SchoolService" , version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.SchoolServiceCodec$Processor")
        trait SchoolService {
        
            /**
            * 

    query the schoolsoa name

            **/
            
            def findSchoolNameById(
            id: String ): String

          
            /**
            * 
            **/
            
            def findSchoolById(
            id: String ): com.today36524.schoolsoa.bean.School

          
            /**
            * 
            **/
            
            def findAllSchool(
            ): List[com.today36524.schoolsoa.bean.School]

          
        }
        