
        package com.today36524.schoolsoa.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.today36524.schoolsoa.service.ScoreService" , version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.ScoreServiceCodec$Processor")
        trait ScoreService {
        
            /**
            * 

    query student

            **/
            
            def findScoreByStudentIdAndLessonName(
            id: String ): com.today36524.schoolsoa.bean.Score

          
            /**
            * 
            **/
            
            def findScoresByStudentId(
            studentId: String ): List[com.today36524.schoolsoa.bean.Score]

          
            /**
            * 
            **/
            
            def findAllScores(
            ): List[com.today36524.schoolsoa.bean.Score]

          
        }
        