
        package com.today36524.schoolsoa.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.today36524.schoolsoa.service.StudentService" , version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.StudentServiceCodec$Processor")
        trait StudentService {
        
            /**
            * 

    query student

            **/
            
            def findStudentById(
            id: String ): com.today36524.schoolsoa.bean.Student

          
            /**
            * 
            **/
            
            def findStudentsByClass(
            classId: String ): List[com.today36524.schoolsoa.bean.Student]

          
            /**
            * 
            **/
            
            def findStudentRowsByClass(
            classId: String ): List[com.today36524.schoolsoa.bean.StudentInfo]

          
        }
        