package com.today36524.schoolsoa.bean

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class School(

         /**
        *
        **/
        
        id : String, /**
        *
        **/
        
        name : String
        )
      