package com.today36524.schoolsoa.bean

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class StudentInfo(

         /**
        *
        **/
        
        id : String, /**
        *
        **/
        
        name : String, /**
        *
        **/
        
        sex : String, /**
        *
        **/
        
        sex_cn : String, /**
        *
        **/
        
        class_id : String, /**
        *
        **/
        
        yuwen : Int, /**
        *
        **/
        
        shuxue : Int, /**
        *
        **/
        
        yingyu : Int, /**
        *
        **/
        
        total : Int, /**
        *
        **/
        
        average : Int
        )
      